use cmhk_validation;
ALTER TABLE `order_info`
ADD COLUMN `speed_test_ref_no` INT DEFAULT NULL COMMENT '速度测试参考号',
ADD COLUMN `speed_test_IP` VARCHAR(50) DEFAULT NULL COMMENT '速度测试IP',
ADD COLUMN `SN_code` VARCHAR(100) DEFAULT NULL COMMENT 'SN编码',
ADD COLUMN `ocr_contract_id` VARCHAR(100) DEFAULT NULL COMMENT 'OCR合同ID';




create table order_info
(
    job_no                       varchar(64)  not null comment '工单唯一ID'
        primary key,
    contract_id                  varchar(64)  null,
    title                        varchar(255) null,
    order_type                   varchar(255) null comment '需要注明所有类型的值及含义：CSF=安装 CSA=维修 RC=重配 CSF(R)搬迁',
    create_date                  datetime     null comment '下单时间',
    customer_order_id            varchar(255) null comment 'CRM订单号',
    customer_sub_order_id        varchar(255) null comment '子工单编号',
    rate_plan                    varchar(255) null,
    service_type                 varchar(255) null comment '需要注明所有类型的值及含义',
    order_status                 varchar(255) null comment '需要注明所有类型的值及含义',
    current_link                 varchar(255) null comment '工单当前所处环节; 需要注明所有类型的值及含义',
    appointment_date             datetime     null comment '预约上门时间',
    arrive_time                  datetime     null comment '装维师傅实际上门时间',
    archive_time                 datetime     null comment '工单归档时间',
    worker_id                    varchar(64)  null comment '装维师傅账号ID',
    worker_name                  varchar(255) null comment '装维师傅名称',
    worker_partner               varchar(255) null comment '装维师傅所属合作商',
    result_code                  varchar(255) null comment '结果编码; 需要注明所有类型的值及含义',
    result_code_desc             varchar(255) null comment '结果编码描述',
    customer_id                  varchar(11)  null comment '客户编号',
    customer                     varchar(255) null comment '客户联系人',
    customer_contact             varchar(32)  null comment '客户联系电话',
    customer_address             varchar(255) null comment '客户地址',
    address_code                 varchar(255) null comment '安装地址编码',
    area                         varchar(255) null comment '总区',
    region                       varchar(255) null comment '地区',
    district                     varchar(255) null comment '分区',
    cmhk_building_id             varchar(32)  null comment '港府楼宇ID',
    build_name                   varchar(255) null comment '屋苑/大厦名称',
    business_type                varchar(255) null comment '业务类型',
    task_category                varchar(255) null comment '任务类型',
    task_sub_category            varchar(255) null comment '任务子类型',
    bandwidth                    varchar(32)  null comment '频宽',
    splitter_id                  varchar(32)  null,
    splitting_ratio              varchar(255) null,
    fm_id                        varchar(255) null,
    fm_port_no                   varchar(32)  null,
    fm_name                      varchar(255) null,
    fm_carrier                   varchar(255) null comment 'FM所属承包商',
    facility_type                varchar(255) null comment '楼宇布线类型',
    pre_wiring                   varchar(255) null comment '楼宇是否预布线',
    pon_port                     varchar(255) null comment 'PON端口',
    olt_name                     varchar(255) null comment '名称应该是唯一的，可以去资管匹配',
    olt_vendor                   varchar(255) null,
    olt_type                     varchar(255) null,
    olt_ip                       varchar(255) null comment 'OLT所属承包商',
    olt_carrier                  varchar(255) null,
    ont_vendor                   varchar(255) null,
    ont_old_sn                   varchar(255) null comment '旧的ONT序列号',
    ont_new_sn                   varchar(255) null comment '新的ONT序列号',
    router_type                  varchar(255) null comment '路由类型',
    router_sn                    varchar(255) null comment '路由序列号',
    olt_tx_opt_power             varchar(255) null comment 'OLT发射光功率',
    ont_rx_opt_power             varchar(255) null comment 'ONT接收光功率',
    ont_tx_opt_power             varchar(255) null comment 'ONT发射光功率',
    olt_rx_opt_power             varchar(255) null comment 'OLT接收光功率',
    speed_test_result            varchar(255) null comment '测速图片地址url',
    download_speed               varchar(255) null comment '下载速率',
    download_speed_manual        varchar(10)  null comment '下载速率是否人工填写：Y/N',
    upload_speed                 varchar(255) null comment '上传速率',
    upload_speed_manual          varchar(10)  null comment '上传速率是否人工填写：Y/N',
    fm_output_power_snapshot     varchar(255) null comment '楼层光功率照片地址url',
    fm_output_power              varchar(255) null comment '楼层光功率数值',
    fm_output_power_manual       varchar(10)  null comment '楼层光功率是否人工填写：Y/N',
    odb_power_meter_snapshot     varchar(255) null comment '插座光功率照片',
    odb_power_meter              varchar(255) null comment '插座光功率数值',
    odb_power_meter_manual       varchar(10)  null comment '插座光功率是否人工填写：Y/N',
    ont_led_status               text         null comment '三张图片:ONT正方面&工单合约编号
地址URL，多个用英文逗号隔开',
    ont_led_light_manual         varchar(10)  null comment 'LED状态灯状态是否人工填写：Y/N',
    line_label_manual            varchar(10)  null comment '线路标签是否人工填写：Y/N',
    ont_label_manual             varchar(10)  null comment 'ONT标签合同号是否人工填写：Y/N',
    signed_uat                   varchar(255) null comment '上传的图片地址URL',
    before_activity_photo        varchar(255) null comment '上传的图片地址URL',
    floor_difference             varchar(20)  null comment 'FM与客户地址楼层差',
    current_handler              varchar(255) null comment '工单当前处理人名称',
    item_status                  varchar(10)  null comment '特殊项验收结果:Y-通过;N-未通过;todo-待验收;空值:不需要验收',
    quality_status               varchar(255) null comment '质量验收结果:Y-人工通过;N-人工未通过;空值:不需要验收;autoSuccess-自动验收通过;autoFail-自动验收失败',
    quality_remark               varchar(255) null comment '质量验收备注',
    optical_power_auto__result   varchar(255) null,
    optical_power_manual__result varchar(255) null,
    speed_auto_result            varchar(255) null,
    speed_manual_result          varchar(255) null,
    is_charge                    varchar(10)  null comment '是否计算ITEM并收取费用:YES/NO，主要用于区分是否保修期内的维修单',
    wifi_plan                    varchar(255) null comment '从大数据平台同步的WIFI Report结果中获取',
    s_vlan                       varchar(64)  null,
    c_vlan                       varchar(64)  null,
    optical_power_auto_result    text         null,
    optical_power_manual_result  text         null,
    ocr_contract_id              varchar(255) null,
    sn_code                      varchar(255) null,
    speed_test_ip                varchar(255) null,
    speed_test_ref_no            int          null
)
    charset = utf8
    row_format = DYNAMIC;

